- hosts: docker
  become: yes
  vars:
    user: lighttpd
    group: lighttpd
  tasks:
  - name: Verificando Distribuição
    set_fact:
      user: www-data
      group: www-data
    when: ansible_distribution|lower == 'debian'
  - name: Garantindo o epel-release em CentOS
    package:
      name: epel-release
      state: present
    when: ansible_distribution|lower == 'centos'
  - name: Garantindo LigHttpd
    package:
      name: [ 'lighttpd', 'git']
      state: present
  - name: Garantindo configurações
    template:
      src: '{{ item }}'
      dest: /etc/lighttpd
      owner: root
      group: root
    loop:
    - /root/playbooks/files/lighttpd.conf
    - /root/playbooks/files/mime-types.conf
  - name: Garatindo Diretórios
    file:
      path: '{{ item }}'
      owner: '{{ user }}'
      group: '{{ group }}'
      state: directory
    loop:
    - /srv/www/html
    - /var/cache/lighttpd
    - /var/logs/lighttpd
  - name: Garantindo Serviço
    service:
      name: lighttpd
      state: started
      enabled: yes
  - name: Removendo arquivos de /srv/www/html
    shell: 'find /srv/www/html/ -delete -mindepth 1'
  - name: Provisionando site de exemplo
    git:
      repo: http://172.27.11.10:3000/devops/site.git
      dest: /srv/www/html
      force: yes
  - name: Garantindo contexto de /srv/www/html
    command: 'restorecon -R /srv/www/html/'
    when: ansible_distribution|lower == 'centos'
